### ISSUE TITLE
Timeline and Task List

### ISSUE THREAD

**Issue by rowanc1** [ncssm/morgantonscientific2024#4]
- [x] Pull requests in by graduation is May 25th (over next month). This is all coming from @taylorgibson.
- [ ] Give `taylorgibson` access to nccsm on sites.curvenote.com
- [ ] change the default domain to the ncssm.org
- [ ] PDF version is after, this is for the website
- [ ] Printer gets the margin lines, etc. table of contents, front-matter (forward, editors introduction, staff-listing, etc).
    - [ ] Have some way to show the frontmatter on the site(advise on this process)
- [ ] R submissions will create images that are not recognized by PDF, this need changes in MyST
- [ ] PDF template (Due May 12)

**Comment by rowanc1** [comment]
We have deployed!
